import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  image: {
    flex: 4,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    position: 'relative',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.06,
    shadowRadius: 3.84,
    elevation: 3,
  },
  btn_back: {
    backgroundColor: '#FFFFFF',
    borderRadius: 6,
    position: 'absolute',
    width: 40,
    height: 40,
    top: 30,
    left: '5%',
    zIndex: 99,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.06,
    shadowRadius: 1.84,
    elevation: 1,
  },
  wrap_content: {
    flex: 4,
    padding: 25,
    paddingBottom: 0,
  },
  image_product: {
    width: '85%',
    backgroundColor: '#ffffff',
    borderBottomLeftRadius: 60,
  },
  name: {
    fontSize: 18,
    color: '#303030',
    fontWeight: '700',
  },
  content: {
    fontSize: 14,
    lineHeight: 19,
    color: '#606060',
  },
  wrap_price_quantity: {
    marginVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  price: {
    color: '#303030',
    fontSize: 18,
  },
  flex: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  btn_augment: {
    backgroundColor: '#E0E0E0',
    width: 30,
    height: 30,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
  },
  number: {
    fontWeight: '700',
    fontSize: 18,
    color: '#242424',
    marginHorizontal: 16,
  },
  content_top: {
    flex: 0.8,
  },
  wrap_btn: {
    flex: 0.2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 10,
  },
  btn_add_cart: {
    backgroundColor: '#242424',
    paddingVertical: 15,
    borderRadius: 8,
    flex: 0.95,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  btn_favorites: {
    backgroundColor: '#F0F0F0',
    width: 60,
    height: 60,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  text_btn: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '600',
  },
  wrap_star: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  number_star: {
    fontSize: 18,
    color: '#303030',
    fontWeight: '700',
    marginHorizontal: 12,
  },
  label_review: {
    fontWeight: '600',
    color: '#808080',
    marginLeft: 8,
  },
  btnOutline: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderRadius: 8,
    marginRight: 10,
  },
  textBtnOutline: {
    color: '#303030',
    fontSize: 14,
  },
  btn: {
    backgroundColor: '#242424',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  textBtn: {
    color: '#FFFFFF',
    fontSize: 14,
  },
  selectOption: {
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
});
